name: flutter_repository_sqflite
description: Implementation of flutter_repository collections, that houses data in an sqlite database.
version: 1.2.0
homepage: https://github.com/gorolykmaxim/flutter_repository_sqflite

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_repository: ^1.0.0
  sqflite: ^1.1.7+1
  mockito: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter